services:
  users.database:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: users.database
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/users-db-3:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proxyBackend
      
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    ports:
      - "5100:5100"
      - "5101:5101"
    environment:
      - ASPNETCORE_URLS=http://+:5100
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      users.database:
        condition: service_healthy
        restart: true
    networks:
      - proxyBackend
  
  products.api:
    image: products.api
    build:
      context: .
      dockerfile: Services/Products.Api/Dockerfile
    ports:
      - "5200:5200"
      - "5201:5201"
    environment:
      - ASPNETCORE_URLS=http://+:5200
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      products.database:
        condition: service_healthy
    restart: always
    networks:
      - proxyBackend
      
  products.database:
    image: mongo:latest
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: products.database
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./.containers/mongo-db:/data/db
    networks:
      - proxyBackend
        
networks:
  proxyBackend:
    name : proxyBackend
    driver: bridge
