services:
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    ports:
      - "5100:5100"
      - "5101:5101"
    environment:
      - ASPNETCORE_URLS=http://+:5100
    networks:
      - proxyBackend
        
networks:
  proxyBackend:
    name : proxyBackend
    driver: bridge
